- src/SourceCode.Clay.Tests/StringExtensionsTests.cs
- src/SourceCode.Clay/StringExtensions.cs
> StringExtensions

- src/SourceCode.Clay.Collections.Tests/DictionaryTests.cs
- src/SourceCode.Clay.Collections/Dictionary.cs
- src/SourceCode.Clay.Collections/ReadOnlyDictionary.cs
> Clay.collections

- SourceCode.Clay.sln
- nuget.config
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/BufferComparer.cs
- src/SourceCode.Clay.Buffers/BufferSession.cs
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Tests/DictionaryTests.cs
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/BaseSwitchBuilder.cs
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data.Tests/SqlConnectionStringBuilderTests.cs
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Data/SqlClient/Azure/SqlConnectionStringBuilderExtensions.cs
- src/SourceCode.Clay.Data/SqlClient/SqlCommandExtensions.cs
- src/SourceCode.Clay.Data/SqlClient/SqlConnectionExtensions.cs
- src/SourceCode.Clay.Data/SqlClient/SqlConnectionRetryOptions.cs
- src/SourceCode.Clay.Data/SqlClient/SqlConnectionStringBuilderExtensions.cs
- src/SourceCode.Clay.Data/SqlClient/SqlDataReaderExtensions.cs
- src/SourceCode.Clay.Json.Tests/JsonExtensionsTests.cs
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay/SafeRandom.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
- netcoreapp2.0
- Remove CodeContracts
> - JsonExtensions -Remove CodeContracts

- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Tests/ListExtensionsFixtures.cs
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/ListExtensions.cs
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Tests/DateTimeExtensionsTests.cs
- src/SourceCode.Clay.Tests/EquatableExtensionsTests.cs
- src/SourceCode.Clay.Tests/ExceptionExtensionsTests.cs
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay/EquatableExtensions.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
> SourceCode.Clay.EquatableExtensions

- src/SourceCode.Clay.Tests/NumberTests.cs
- src/SourceCode.Clay/Number.cs
- Adding Number to Clay.
- Number is a discriminated union of: SByte, Byte, Int16, UInt16, Int32, UInt32, Int64, UInt64, Single, Double.
> Number Type

- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay/SourceCode.Clay.csproj
> netcoreapp2.0

- src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs
- src/SourceCode.Clay.Buffers/ArrayBufferComparer.cs
- src/SourceCode.Clay.Buffers/BufferComparer.cs
- src/SourceCode.Clay.Buffers/EnumerableBufferComparer.cs
- src/SourceCode.Clay.Buffers/ListBufferComparer.cs
- src/SourceCode.Clay.Buffers/ReadOnlySpanBufferComparer.cs
> BufferComparer does not work for empty array

- src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs
- src/SourceCode.Clay.Buffers/ArrayBufferComparer.cs
- src/SourceCode.Clay.Buffers/BufferComparer.T.cs
- src/SourceCode.Clay.Buffers/EnumerableBufferComparer.cs
- src/SourceCode.Clay.Buffers/ListBufferComparer.cs
- src/SourceCode.Clay.Buffers/ReadOnlyListBufferComparer.cs
- src/SourceCode.Clay.Buffers/SpanBufferComparer.cs
> Fix null handling in GetHashCode

- .editorconfig
- Directory.Build.props
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/HashCode.Fnv.cs
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/ListExtensions.cs
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/OrdinalIgnoreCaseString.cs
- src/SourceCode.Clay.Text/OrdinalString.cs
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay/SourceCode.Clay.csproj
> Update build config

- src/SourceCode.Clay.Tests/SemanticVersionComparerTests.cs
- src/SourceCode.Clay.Tests/SemanticVersionTests.cs
- src/SourceCode.Clay/SemanticVersion.cs
- src/SourceCode.Clay/SemanticVersionComparer.cs
- src/SourceCode.Clay/SemanticVersionCompatabilities.cs
- src/SourceCode.Clay/SemanticVersionIncompatabilities.cs
Adding `SemanticVersion` type.
> Semantic Version

- src/SourceCode.Clay.Tests/NumberTests.cs
- src/SourceCode.Clay/Number.cs
Adds decimal support to number, as well as some cleanups.
- Adding decimal type to Number.
- Adding ToDecimal method.
- Returning field directly in conversion methods, when the type matches.
- Fixing some bugs in the Number tests.
Fixes #48.
> Decimal support for Number

- .editorconfig
- src/SourceCode.Clay.Collections.Tests/DictionaryExtensionsTests.cs
- src/SourceCode.Clay.Collections.Tests/DictionaryTests.cs
- src/SourceCode.Clay.Collections.Tests/KeyedLookupTests.cs
- src/SourceCode.Clay.Collections.Tests/ListExtensionsTests.cs
- src/SourceCode.Clay.Collections.Tests/SetExtensionsTests.cs
- src/SourceCode.Clay.Collections.Tests/SpanExtensionsTests.cs
- src/SourceCode.Clay.Collections.Tests/SwitchExtensionsTests.cs
- src/SourceCode.Clay.Collections/DictionaryExtensions.cs
- src/SourceCode.Clay.Collections/KeyedCollectionFactory.cs
- src/SourceCode.Clay.Collections/ListExtensions.cs
- src/SourceCode.Clay.Collections/SetExtensions.cs
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Collections/SpanExtensions.cs
- src/SourceCode.Clay.Data/SqlParser/SqlParamInfo.cs
- src/SourceCode.Clay.Json.Tests/DecimalValidatorTests.cs
- src/SourceCode.Clay.Json.Tests/LongValidatorTests.cs
- src/SourceCode.Clay.Json.Tests/NumberValidatorTests.cs
- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/Validation/DecimalValidator.cs
- src/SourceCode.Clay.Json/Validation/Int64Validator.cs
- src/SourceCode.Clay.Tests/NumberTests.cs
- src/SourceCode.Clay.Tests/SemanticVersionComparerTests.cs
- src/SourceCode.Clay.Tests/SemanticVersionTests.cs
- src/SourceCode.Clay/Number.cs
- Fixes #62 Add `DecimalValidator`
- Fixes #61 Add `SpanEquals`
- Fixes #60 Rename `NullableEquals`
- Fixes #64 Rename `SetEquals`
- Fixes various comments
- Normalize unit naming (using `nameof`)
- Fixes various parameter names
> Various fixes

- src/SourceCode.Clay.Collections/Dictionary.cs
- src/SourceCode.Clay.Json.Tests/JsonPointerTests.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointer.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointerEvaluationOptions.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointerToken.cs
Adds JSON pointers. These conform to [RFC 6901.](https://tools.ietf.org/html/rfc6901)
> Feature JSON Pointers

- Directory.Build.props
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/ListExtensions.cs
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Data/SqlParser/SqlParamInfo.cs
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/OrdinalIgnoreCaseString.cs
- src/SourceCode.Clay.Text/OrdinalString.cs
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay/Number.cs
- src/SourceCode.Clay/SemanticVersionComparer.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
- Update various project & nuget settings
- Update GetHashCode() pattern
> Fix Project Settings

- CodeMaid.config
- src/SourceCode.Clay.Threading.Tests/ParallelAsyncTests.cs
Per @jcdickinson suggestion, also added codemaid config file
> Add missing units

- Directory.Build.props
- GenerateTestSolution.ps1
- README.md
- SourceCode.Clay.sln
- appveyor.yml
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.OpenApi.Tests/SourceCode.Clay.OpenApi.Tests.csproj
- src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay.Threading.Tests/SourceCode.Clay.Threading.Tests.csproj
- src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj
- src/SourceCode.Clay/SourceCode.Clay.csproj
- Copying code coverage stuff from Chasm
> Code Coverage

- src/SourceCode.Clay.OpenApi.Tests/DtoTests.cs
- src/SourceCode.Clay.OpenApi/License.cs
- src/SourceCode.Clay.OpenApi/OAuth2SecurityScheme.cs
- src/SourceCode.Clay.OpenApi/Operation.cs
- src/SourceCode.Clay.OpenApi/Parameter.cs
- src/SourceCode.Clay.OpenApi/ParameterBody.cs
- src/SourceCode.Clay.OpenApi/RequestBody.cs
- src/SourceCode.Clay.OpenApi/Schema.cs
- src/SourceCode.Clay.OpenApi/SchemaType.cs
- src/SourceCode.Clay/SemanticVersionComparer.cs
Adding unit tests for Open API DTO Equals methods.
- Fixing some bugs in DTOs.
- Removing some old unused stuff.
> Code Coverage: Open API DTO Equals

- src/SourceCode.Clay.OpenApi.Tests/BuilderTests.cs
- src/SourceCode.Clay.OpenApi/Builders/ApiKeySecuritySchemeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/CallbackBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ComponentsBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ContactBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/DocumentBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ExampleBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ExternalDocumentationBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/HttpSecuritySchemeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/IBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/InformationBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/LicenseBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/LinkBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/MediaTypeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/OAuth2SecuritySchemeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/OAuthFlowBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/OpenIdConnectSecuritySchemeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/OperationBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ParameterBodyBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ParameterBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/PathBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/PropertyEncodingBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/RequestBodyBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ResponseBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/SchemaBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/SecuritySchemeBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ServerBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/ServerVariableBuilder.cs
- src/SourceCode.Clay.OpenApi/Builders/TagBuilder.cs
- src/SourceCode.Clay.OpenApi/ParameterKey.cs
Add builder tests.
- Adding IBuilder<TBuilt>
- Adding some missing doccomments.
- Fix some bugs exposed by tests.
Improves #83.
> Code Coverage: OpenAPI Builders

- src/SourceCode.Clay.Tests/EnumConvertTests.cs
- src/SourceCode.Clay/EnumConvert.cs
> EnumConvert.Length

- src/SourceCode.Clay.Collections.Tests/DictionaryExtensionsTests.cs
- src/SourceCode.Clay.Collections/Generic/CollectionExtensions.cs
- src/SourceCode.Clay.Collections/Generic/DictionaryExtensions.cs
- src/SourceCode.Clay.Collections/Generic/EnumerableExtensions.cs
- src/SourceCode.Clay.Collections/Generic/ListExtensions.cs
- src/SourceCode.Clay.Collections/Generic/MemoryExtensions.cs
- src/SourceCode.Clay.Collections/Generic/SetExtensions.cs
- src/SourceCode.Clay.Collections/Generic/SwitchExtensions.cs
> DictionaryExtensions should accept IDictionary

- src/SourceCode.Clay.OpenApi/Path.cs
Open API Path was not immutable.
Fixes #120
> Open API Path is Immutable

- src/SourceCode.Clay.OpenApi.Tests/SerializeTests.cs
- src/SourceCode.Clay.OpenApi/Link.cs
- src/SourceCode.Clay.OpenApi/Operation.cs
- src/SourceCode.Clay.OpenApi/Serialization/OpenApiSerializer.Serialize.cs
- src/SourceCode.Clay.OpenApi/Serialization/OpenApiSerializer.SerializeHelpers.cs
Some serialization bugs with references. Some more types were not immutable. Fixes #125. Actually fixes #120.
> Serialization

- src/SourceCode.Clay.Json.Tests/JsonExtensionsTests.cs
- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/ReadOnlyJsonObject.cs
- src/SourceCode.Clay.OpenApi/Expressions/OasExpressionComponentType.cs
- src/SourceCode.Clay.OpenApi/Expressions/OasFieldExpressionSource.cs
- src/SourceCode.Clay.OpenApi/Expressions/OasFieldExpressionType.cs
- src/SourceCode.Clay.OpenApi/OasOperationOptions.cs
- src/SourceCode.Clay.OpenApi/OasParameterLocation.cs
- src/SourceCode.Clay.OpenApi/OasParameterOptions.cs
- src/SourceCode.Clay.OpenApi/OasParameterStyle.cs
- src/SourceCode.Clay.OpenApi/OasPropertyEncodingOptions.cs
- src/SourceCode.Clay.OpenApi/OasRangeOptions.cs
- src/SourceCode.Clay.OpenApi/OasRequestBodyOptions.cs
- src/SourceCode.Clay.OpenApi/OasSchemaOptions.cs
- src/SourceCode.Clay.OpenApi/OasSchemaType.cs
- src/SourceCode.Clay.OpenApi/OasSecuritySchemeType.cs
> ReadOnlyJsonObject

- src/SourceCode.Clay.Tests/HashCodeTests.cs
- src/SourceCode.Clay/HashCode.cs
- src/SourceCode.Clay/HashCodeExtensions.cs
> Align HashCode to Proposal

- src/SourceCode.Clay.Collections/Generic/EnumerableExtensions.cs
- src/SourceCode.Clay.Json.Tests/JsonExtensionsTests.cs
- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/NumberExtensions.cs
- src/SourceCode.Clay.Json/ReadOnlyJsonObject.cs
> Json equality perf

- src/SourceCode.Clay/HashCode.cs
Prematurely optimizing HashCode into 1 cacheline.
> Premature Optimization 101

- src/SourceCode.Clay.Buffers.Tests/IO/StreamExtensionsTests.cs
- src/SourceCode.Clay.Json.Tests/JsonExtensionsTests.cs
- src/SourceCode.Clay.Json/JsonComparer.cs
- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/ReadOnlyJsonObject.cs
- src/SourceCode.Clay.OpenApi.Tests/Mock/MockOasOperation.cs
- src/SourceCode.Clay.OpenApi.Tests/Mock/MockOasOperationBuilder.cs
- src/SourceCode.Clay.OpenApi.Tests/Mock/MockOasSerializer.cs
- src/SourceCode.Clay.OpenApi.Tests/SerializeTests.cs
- src/SourceCode.Clay.OpenApi/OasContact.cs
- Fixes #155 (again)
- Fixes #158
> JsonComparer

- src/SourceCode.Clay.Collections.Bench/Int32SwitchVsDictionaryBench.cs
- src/SourceCode.Clay.Json.Bench/CloneBench.cs
- src/SourceCode.Clay.Json.Bench/EqualsBench.cs
- src/SourceCode.Clay.Json.Bench/ParseBench.cs
- src/SourceCode.Clay.Json.Bench/Program.cs
- src/SourceCode.Clay.Json.Bench/SourceCode.Clay.Json.Bench.csproj
- src/SourceCode.Clay.Json.Bench/ToStringBench.cs
- src/SourceCode.Clay.Json/JsonValueComparer.cs
Fixes #164
Add benchmarks to test performance of various algorithms. In this case, performance of Json operations.
* Added benchmarks
> Add Newtonsoft benchmarks

- src/SourceCode.Clay.Json/JsonExtensions.cs
- src/SourceCode.Clay.Json/JsonValueComparer.cs
- src/SourceCode.Clay.Tests/HashCodeTests.cs
Refactor the code to remove some of its complexity
> Simplify Json Clone and Equals

- src/SourceCode.Clay.Json/JsonReaderExtensions.Array.cs
- src/SourceCode.Clay.Json/JsonReaderExtensions.Object.cs
Mistakenly deleted code being used elsewhere.
This PR undeletes it.
> Undelete code

- src/SourceCode.Clay.Json/Pointers/JsonPointer.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointerToken.cs
`JsonPointer` should provide an (immutable) `Add` operation.
> JsonPointer enhancements

- src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs
- src/SourceCode.Clay.Buffers.Tests/IO/MemoryBufferStreamTests.cs
- src/SourceCode.Clay.Buffers.Tests/IO/StreamExtensionsTests.cs
- src/SourceCode.Clay.Buffers/IO/MemoryBufferStream.cs
A stream that allows you to read from ReadOnlyMemory<byte>.
Fixes #199
> Memory Buffer Stream

- src/SourceCode.Clay.Buffers.Tests/BufferSessionTests.cs
- src/SourceCode.Clay.Buffers/BufferSession.cs
- src/SourceCode.Clay.Buffers/IO/BufferSessionStream.cs
- src/SourceCode.Clay.Buffers/IO/CompletedWaitHandle.cs
- src/SourceCode.Clay.Buffers/IO/MemoryBufferStream.cs
- src/SourceCode.Clay.Buffers/IO/StreamExtensions.cs
- src/SourceCode.Clay.Buffers/IO/SyncAsyncResult.cs
- src/SourceCode.Clay.OpenApi/OasDataTypeFormat.cs
- src/SourceCode.Clay.OpenApi/OasHttpSecurityScheme.cs
- src/SourceCode.Clay.OpenApi/OasSecurityScheme.cs
- src/SourceCode.Clay.OpenApi/Serialization/OasSerializer.Constants.cs
- src/SourceCode.Clay/EnumConvert.cs
- Clean up BufferSession API.
- Add stream for BufferSession (needs tests).
- Fix some warnings.
Fixes #208 
Introduces #209
> BufferSession Cleanup

- src/SourceCode.Clay.Tests/SecureStringExtensionsTests.cs
- src/SourceCode.Clay.Tests/StringExtensionsTests.cs
- src/SourceCode.Clay.Tests/TestVectors.cs
- src/SourceCode.Clay/SecureStringExtensions.cs
Add `SecureString` extension methods to Clay
> SecureString

- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data.Tests/SqlTokenizerTests.cs
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.Data/SqlParser/SqlTokenizer.cs
- src/SourceCode.Clay.IO.Tests/SourceCode.Clay.IO.Tests.csproj
- src/SourceCode.Clay.IO/SourceCode.Clay.IO.csproj
- src/SourceCode.Clay.Json.Bench/SourceCode.Clay.Json.Bench.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/Pointers/JsonPointer.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointerToken.cs
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.OpenApi.Tests/SourceCode.Clay.OpenApi.Tests.csproj
- src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay.Threading.Tests/SourceCode.Clay.Threading.Tests.csproj
- src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj
- src/SourceCode.Clay/SemanticVersion.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
- Utility functions
- Nuget
- FxCop
> SqlTokenizer.QuoteName

- SourceCode.Clay.sln
- src/SourceCode.Clay.Algorithms.Tests/GraphTests.cs
- src/SourceCode.Clay.Algorithms.Tests/SourceCode.Clay.Algorithms.Tests.csproj
- src/SourceCode.Clay.Algorithms/Edge.cs
- src/SourceCode.Clay.Algorithms/Graph.Nested.cs
- src/SourceCode.Clay.Algorithms/Graph.RepresentativeForest.cs
- src/SourceCode.Clay.Algorithms/Graph.cs
- src/SourceCode.Clay.Algorithms/Graph.md
- src/SourceCode.Clay.Algorithms/SourceCode.Clay.Algorithms.csproj
- src/SourceCode.Clay.Algorithms/TreeNode.cs
Fixes #219
More information in Graph.md.
> Representative Forest

- src/SourceCode.Clay.Buffers/IO/BufferSessionStream.cs
- src/SourceCode.Clay.Json/Pointers/JsonPointer.cs
- src/SourceCode.Clay.OpenApi/Builders/OasCallbackBuilder.cs
- src/SourceCode.Clay.OpenApi/Expressions/OasExpression.cs
- src/SourceCode.Clay.OpenApi/OasCallback.cs
- src/SourceCode.Clay.OpenApi/OasComponentKeyStringComparer.cs
- src/SourceCode.Clay.OpenApi/OasReference.cs
- src/SourceCode.Clay.OpenApi/OasScalarValue.cs
> Clear all warnings

- src/SourceCode.Clay.Json/LinkedData/LinkedDataOptions.cs
> Fix broken web request

- src/SourceCode.Clay.Tests/Sha1Tests.cs
- src/SourceCode.Clay/Sha1.cs
> Issue 235 - Sha1.Zero is bad design

- src/SourceCode.Clay.Json.Tests/NumberTests.cs
- src/SourceCode.Clay.Json/Number.cs
- src/SourceCode.Clay.Json/NumberComparer.cs
- src/SourceCode.Clay.Json/NumberKinds.cs
- src/SourceCode.Clay.OpenApi/OasScalarValue.cs
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
The primary consumer of Number is Json, so move it there
> Move Number to Clay.Json

- src/SourceCode.Clay.Algorithms.Tests/SourceCode.Clay.Algorithms.Tests.csproj
- src/SourceCode.Clay.Buffers.Tests/BlitTests.cs
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/Blit.cs
- src/SourceCode.Clay.Buffers/IO/MemoryBufferStream.cs
- src/SourceCode.Clay.Buffers/SpanExtensions.cs
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.IO.Tests/SourceCode.Clay.IO.Tests.csproj
- src/SourceCode.Clay.Json.Bench/SourceCode.Clay.Json.Bench.csproj
- src/SourceCode.Clay.Json.Tests/JsonReaderExtensionTests.cs
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/JsonReaderExtensions.cs
- src/SourceCode.Clay.OpenApi.Tests/SourceCode.Clay.OpenApi.Tests.csproj
- src/SourceCode.Clay.Security.Tests/SourceCode.Clay.Security.Tests.csproj
- src/SourceCode.Clay.Security/SafeRandom.cs
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Threading.Tests/SourceCode.Clay.Threading.Tests.csproj
- src/SourceCode.Clay/Sha1.cs
* Various optimizations
* JsonReaderExtensions
* Nuget
> More Optimizations

- src/SourceCode.Clay.Algorithms.Tests/SourceCode.Clay.Algorithms.Tests.csproj
- src/SourceCode.Clay.Algorithms/SourceCode.Clay.Algorithms.csproj
- src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.IO.Tests/SourceCode.Clay.IO.Tests.csproj
- src/SourceCode.Clay.IO/SourceCode.Clay.IO.csproj
- src/SourceCode.Clay.Javascript.Tests/SourceCode.Clay.Javascript.Tests.csproj
- src/SourceCode.Clay.Javascript/SourceCode.Clay.Javascript.csproj
- src/SourceCode.Clay.Json.Bench/SourceCode.Clay.Json.Bench.csproj
- src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.OpenApi.Tests/SourceCode.Clay.OpenApi.Tests.csproj
- src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj
- src/SourceCode.Clay.Security.Tests/SourceCode.Clay.Security.Tests.csproj
- src/SourceCode.Clay.Security/SourceCode.Clay.Security.csproj
- src/SourceCode.Clay.Tests/Sha1Tests.cs
- src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj
- src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay.Threading.Tests/SourceCode.Clay.Threading.Tests.csproj
- src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj
- src/SourceCode.Clay/MemoryExtensions.cs
- src/SourceCode.Clay/Sha1.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
- src/SourceCode.Clay/StringExtensions.cs
- Add [SourceLink](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md)
- Optimize StringExtensions.Left/Right
- Add corresponding MemoryExtensions.Left(Span)/Right(Span)
> Nuget & MemoryExtensions

- src/SourceCode.Clay.Algorithms/SourceCode.Clay.Algorithms.csproj
- src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj
- src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj
- src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj
- src/SourceCode.Clay.IO/SourceCode.Clay.IO.csproj
- src/SourceCode.Clay.Javascript/SourceCode.Clay.Javascript.csproj
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj
- src/SourceCode.Clay.Security/SourceCode.Clay.Security.csproj
- src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj
- src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj
- src/SourceCode.Clay/Sha1.cs
- src/SourceCode.Clay/Sha256.cs
- src/SourceCode.Clay/ShaUtil.cs
- src/SourceCode.Clay/SourceCode.Clay.csproj
- src/SourceCode.Clay/StringExtensions.cs
* `Sha1.ToHex` is non-optimal
* Nuget
* Clean up code, conventions
* Add `string.RemovePrefix`
> Optimize ToHex

- src/SourceCode.Clay/Sha1.cs
- src/SourceCode.Clay/Sha1Extensions.cs
- src/SourceCode.Clay/Sha256.cs
- src/SourceCode.Clay/Sha256Extensions.cs
- src/SourceCode.Clay/SourceCode.Clay.xml
- tests/SourceCode.Clay.Tests/Sha1Tests.cs
- tests/SourceCode.Clay.Tests/Sha256Tests.cs
Phase 2. Details in previous PR
> Remove obsoleted sha1 members

- Directory.Build.props
- src/SourceCode.Clay/DecorrelatedJitter.cs
- src/SourceCode.Clay/EnumConvert.cs
- src/SourceCode.Clay/ExceptionExtensions.cs
- src/SourceCode.Clay/NumericExtensions.cs
- src/SourceCode.Clay/RandomExtensions.cs
- tests/SourceCode.Clay.Algorithms.Bench/SourceCode.Clay.Algorithms.Bench.csproj
- tests/SourceCode.Clay.Buffers.Bench/SourceCode.Clay.Buffers.Bench.csproj
- tests/SourceCode.Clay.Collections.Bench/SourceCode.Clay.Collections.Bench.csproj
- tests/SourceCode.Clay.Json.Bench/SourceCode.Clay.Json.Bench.csproj
- tests/SourceCode.Clay.Tests/DecorrelatedJitterTests.cs
- tests/SourceCode.Clay.Tests/EnumConvertTests.cs
- tests/SourceCode.Clay.Tests/ExceptionExtensionsTests.cs
- tests/SourceCode.Clay.Tests/NumericExtensionsTests.cs
- tests/SourceCode.Clay.Tests/RandomExtensionsTests.cs
- `RandomExtensions`
- `NumericExtensions`
- `ExceptionExtentions`
- `DecorrelatedJitter`
- `EnumExtensions`
- `<PackageRequireLicenseAcceptance>FALSE</>`
- Nuget
- Units
> Various extensions & units

- src/SourceCode.Clay.IO/SeekableStream.cs
- src/SourceCode.Clay.IO/SourceCode.Clay.IO.csproj
- tests/SourceCode.Clay.IO.Tests/SeekableStream.Tests.cs
- tests/SourceCode.Clay.IO.Tests/StreamWrapper.cs
* .IO is now NetStandard.
* Adding SeekableStream, which can be used to make a non-seekable stream seekable.
> SeekableStream

- src/SourceCode.Clay.Threading/AsyncLock.cs
- src/SourceCode.Clay.Threading/AsyncLockCookie.cs
- src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj
- tests/SourceCode.Clay.Threading.Tests/AsyncLockTests.cs
Low allocation lock (zero if there is no contention) that can be used in async.
> Async Lock

- git-feature.bat
Run git-feature \<branch\>
This will:
1. Fetch upstream master.
2. Create the branch
3. Publish the branch to your fork.
> Adding Feature Script

- Directory.Build.props
- src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj
- src/SourceCode.Clay.Security/CertificateLoader.cs
* Update Nuget
* Fix comments
* Add the following methods:
```csharp
X509Certificate2 LoadCertificate(StoreName storeName, StoreLocation storeLocation, string subject, string issuer, bool validOnly)
bool TryLoadCertificate(StoreName storeName, StoreLocation storeLocation, string subject, string issuer, bool validOnly, out X509Certificate2 certificate)
bool TryLoadCertificate(string fileName, SecureString password, out X509Certificate2 certificate)
```
> Add certificate methods
