src/SourceCode.Clay.Collections/Dictionary.cs, src/SourceCode.Clay.Collections/ReadOnlyDictionary.cs
Similar pattern to Array.Empty<T>(). 
Useful for assigning an empty dictionary, without allocating memory.
=> Dictionary.Empty

src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs, src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj, src/SourceCode.Clay.Buffers/BufferComparer.cs, src/SourceCode.Clay.Buffers/BufferSession.cs, src/SourceCode.Clay.Buffers/HashCode.Fnv.cs, src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj, src/SourceCode.Clay.Collections.Tests/DictionaryTests.cs, src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj, src/SourceCode.Clay.Collections/Dictionary.cs, src/SourceCode.Clay.Collections/ReadOnlyDictionary.cs, src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj, src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj, src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj, src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj, src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj, src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj, src/SourceCode.Clay/SourceCode.Clay.csproj
- Upgraded all projects to NetCoreApp2.0
- Elided Span<T> and Buffer<T> functionality from BufferComparer, due to build issues at caller
- Use StringComparer.Ordinal.Equals instead of string.Equals(..., StringComparison.Ordinal)
- byte[] is implicitly convertible to Span<byte> so no need for methods to override both signatures
- Normalized project settings and Nugets
=> NetCoreApp2.0 prep

src/SourceCode.Clay.Data.Tests/SqlTokenizerTests.cs, src/SourceCode.Clay.Data/SqlParser/SqlTokenInfo.cs, src/SourceCode.Clay.Data/SqlParser/SqlTokenizer.cs
Tokenizer is not parsing comments properly - it breaks when the CLR is on Linux (where the line-endings are `\n` and not `\r\n` like on Windows)
=> Fix SqlTokenizer

src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs, src/SourceCode.Clay.Buffers/BufferComparer.cs
Fixes #37 
- Also add more units
- Fix bugs in how ArraySegment is handled
=> BufferComparer should use fast path when array is length 1

src/SourceCode.Clay.Buffers.Tests/BlitTests.cs, src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs, src/SourceCode.Clay.Buffers/ArrayBufferComparer.cs, src/SourceCode.Clay.Buffers/BufferComparer.T.cs, src/SourceCode.Clay.Buffers/BufferComparer.cs, src/SourceCode.Clay.Buffers/BufferSession.cs, src/SourceCode.Clay.Buffers/HashCode.Fnv.cs, src/SourceCode.Clay.Buffers/SpanBufferComparer.cs, src/SourceCode.Clay/Number.cs
Fixes #46 
- Full HashCodeFidelity is represented by 0 instead of -1
- Add `Comparison` delegate to BufferComparers
- Comments
- Some TODOs that are predicated on C#7.x compiler availability
=> BufferComparer

src/SourceCode.Clay.Buffers.Tests/SourceCode.Clay.Buffers.Tests.csproj, src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj, src/SourceCode.Clay.Collections.Tests/SourceCode.Clay.Collections.Tests.csproj, src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj, src/SourceCode.Clay.Data.Tests/SourceCode.Clay.Data.Tests.csproj, src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj, src/SourceCode.Clay.Json.Tests/SourceCode.Clay.Json.Tests.csproj, src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj, src/SourceCode.Clay.Tests/SourceCode.Clay.Tests.csproj, src/SourceCode.Clay.Tests/StringExtensionsTests.cs, src/SourceCode.Clay.Text.Tests/SourceCode.Clay.Text.Tests.csproj, src/SourceCode.Clay.Text/OrdinalIgnoreCaseString.cs, src/SourceCode.Clay.Text/OrdinalString.cs, src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj, src/SourceCode.Clay/SourceCode.Clay.csproj, src/SourceCode.Clay/StringExtensions.cs
Fixes #52 (surrogate-pair)
Fixes #50 (Nuget License)
- `OrdinalString` should implement `IComparable<T>`
=> Fix surrogate-pair handling

src/SourceCode.Clay.OpenApi/Builders/ApiKeySecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/CallbackBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ComponentsBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ContactBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/DocumentBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ExampleBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ExternalDocumentationBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/HttpSecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/IOpenApiBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/InformationBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/LicenseBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/LinkBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/MediaTypeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OAuth2SecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OAuthFlowBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OpenIdConnectSecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OperationBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ParameterBodyBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ParameterBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/PathBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/PropertyEncodingBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/RequestBodyBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ResponseBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/SchemaBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ServerBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ServerVariableBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/TagBuilder.cs, src/SourceCode.Clay.Tests/EnumConvertTests.cs, src/SourceCode.Clay/EnumConvert.cs
Adding EnumConvert class that allows you to cast enums to integers. Both Checked and unchecked variants are provided. The C# `where Enum` trick is NOT used as it can crash the compiler.
Also renaming IBuilder to IOpenApiBuilder as this can conflict with interfaces from other assemblies easily.
Fixes #90.
=> EnumConvert

src/SourceCode.Clay.OpenApi.Tests/DtoTests.cs, src/SourceCode.Clay.OpenApi.Tests/SerializeTests.cs, src/SourceCode.Clay.OpenApi/Builders/ApiKeySecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/CallbackBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ComponentsBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ExampleBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/HttpSecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/LinkBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OAuth2SecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OpenIdConnectSecuritySchemeBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/OperationBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ParameterBodyBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ParameterBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/PathBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/RequestBodyBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/ResponseBuilder.cs, src/SourceCode.Clay.OpenApi/Builders/SchemaBuilder.cs, src/SourceCode.Clay.OpenApi/ComponentKeyStringComparer.cs, src/SourceCode.Clay.OpenApi/IReferable.cs, src/SourceCode.Clay.OpenApi/Operation.cs, src/SourceCode.Clay.OpenApi/ParameterOptions.cs, src/SourceCode.Clay.OpenApi/Referable.cs, src/SourceCode.Clay.OpenApi/Serialization/IOpenApiSerializer.cs, src/SourceCode.Clay.OpenApi/Serialization/NumberExtensions.cs, src/SourceCode.Clay.OpenApi/Serialization/OpenApiSerializer.cs
Implementing serialization (but not deserialization) for OpenAPI. Partial #85.
- Adding a comparer for component names (improves #80).
- Adding implicit operations for Referable<> where applicable.
- Change Parameter to ParameterBody for Operation.
=> OpenAPI JSON Serialization

src/SourceCode.Clay.OpenApi/Serialization/OpenApiSerializer.Serialize.cs
Turns out that the .Net JITter does not optimize `typeof(T) == typeof(Foo)`. Using the jump table that already exists in SerializeUnknown.
``` ini
BenchmarkDotNet=v0.10.9.321-nightly, OS=Windows 10 Redstone 2 [1703, Creators Update] (10.0.15063.674)
Processor=Intel Core i7-4800MQ CPU 2.70GHz (Haswell), ProcessorCount=8
Frequency=2630626 Hz, Resolution=380.1377 ns, Timer=TSC
[Host]     : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2115.0
DefaultJob : .NET Framework 4.6.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2115.0
```
|             Method |     Mean |     Error |    StdDev |
|------------------- |---------:|----------:|----------:|
|       IfStatements | 906.7 ns | 17.918 ns | 16.761 ns |
| CachedIfStatements | 596.7 ns |  5.664 ns |  5.298 ns |
|          JumpTable | …
=> Serialize Jump Table

src/SourceCode.Clay.OpenApi.Tests/SerializeTests.cs, src/SourceCode.Clay.OpenApi/Builders/DocumentBuilder.cs, src/SourceCode.Clay.OpenApi/Serialization/OpenApiSerializer.Serialize.cs
Fixing some bugs
- DocumentBuilder defaults to version 3.0.0 now.
- RequestBody.Required was serializing as "requestBodies"
=> OpenAPI Bugs

src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs, src/SourceCode.Clay.Buffers.Tests/IO/StreamExtensionsTests.cs, src/SourceCode.Clay.Buffers/IO/StreamExtensions.cs, src/SourceCode.Clay/IO/FileLock.cs
Adding FileLock and StreamExtensions. FileLock is for acquiring locks on files, while StreamExtensions helps with working with ReadOnlyMemory and Span on Streams.
Fixes #130 and fixes #131.
=> System.IO Extensions

src/SourceCode.Clay.Buffers.Tests/BufferComparerTests.cs, src/SourceCode.Clay.Buffers/ArrayBufferComparer.cs, src/SourceCode.Clay.Buffers/BinaryHashCode.Fnv.cs, src/SourceCode.Clay.Buffers/MemoryBufferComparer.cs, src/SourceCode.Clay.Tests/HashCodeTests.cs, src/SourceCode.Clay/HashCode.cs, src/SourceCode.Clay/HashCodeExtensions.cs
Fix #142: Align the interface with the proposal. Add extension methods because the proposal lacks DRY.
Fix #141: Rename HashCode.Fnv to BinaryHashCode.Fnv.
=> HashCode Parity

src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj, src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj, src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj, src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj, src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj, src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj, src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj, src/SourceCode.Clay/SourceCode.Clay.csproj
Fixes: Build-specific Nugets should use `PrivateAssets=All`
=> Nuget (PrivateAssets All)

src/SourceCode.Clay.Json.Tests/JsonExtensionsTests.cs, src/SourceCode.Clay.Json/JsonExtensions.cs, src/SourceCode.Clay.Json/JsonValueComparer.cs, src/SourceCode.Clay.Json/ReadOnlyJsonObject.cs
`JsonComparer` is unnecessarily complex, this PR tightens the code.
=> Simplify & rename JsonValueComparer

src/SourceCode.Clay.Tests/HashCodeTests.cs, src/SourceCode.Clay/HashCodeExtensions.cs
Fixes #
Additional extension methods & default parameters for `HashCodeExtensions`
- All `Tally` methods have a `coalesce` parameter which is used in the hashcode if the main value is `null`
- An additional `Tally` method that supports `Nullable<T>`
Not sure if `coalesce` is the best name.
=> Add coalesce parameter to HashCode.Tally

src/SourceCode.Clay.Tests/Sha1Tests.cs, src/SourceCode.Clay.Tests/TestVectors.cs, src/SourceCode.Clay/Sha1.cs, src/SourceCode.Clay/Sha1Comparer.cs, src/SourceCode.Clay/SourceCode.Clay.csproj
Fixes #192 
`Sha1` is useful outside of the other infrastructure provided by `Chasm`
* Move `Sha1` and related classes to `Clay` from `Chasm`
=> Fix #192 Move Sha1 to Clay from Chasm

src/SourceCode.Clay.Json.Tests/LinkedData/Cases/expand-0078-in.jsonld, src/SourceCode.Clay.Json.Tests/LinkedData/Cases/expand-0078-out.jsonld, src/SourceCode.Clay.Json.Tests/LinkedData/Cases/expand-manifest.jsonld, src/SourceCode.Clay.Json.Tests/LinkedData/LinkedDataTestCase.cs, src/SourceCode.Clay.Json.Tests/LinkedData/LinkedDataTransformationTests.cs, src/SourceCode.Clay.Json/LinkedData/LinkedDataContext.cs, src/SourceCode.Clay.Json/LinkedData/LinkedDataOptions.cs
Fixes #228
The previous context in the chain was being ignored (only the initial empty context was being honored).
- Add tests for remote contexts.
- Fix bug with remote context chaining.
- Ensure that LinkedDataOptions can be inherited in a useful way.
=> Remote Context Chaining Fix

src/SourceCode.Clay.Algorithms/Edge.cs, src/SourceCode.Clay.Algorithms/Graph.Nested.cs, src/SourceCode.Clay.Algorithms/Graph.RepresentativeForest.cs, src/SourceCode.Clay.Algorithms/Graph.Tarjan.cs, src/SourceCode.Clay.Algorithms/Graph.cs, src/SourceCode.Clay.Algorithms/SourceCode.Clay.Algorithms.csproj, src/SourceCode.Clay.Algorithms/TreeNode.cs
Fixes #233.
* Add DocComments
* Improve behavior of `TreeNode<T>.GetHashCode`
* TreeNode.Clone uses explicit array copy to guarantee one allocation.
* Warnings from `Graph<T>.Nested` for some reason, disabled warnings for the file.
=> Graph DocComments and Tweaks

src/SourceCode.Clay.Buffers.Tests/BitOpsTests.cs, src/SourceCode.Clay.Buffers/BitOps.Span.cs, src/SourceCode.Clay.Buffers/BitOps.cs
- The `offset` parameter is `int` not `byte`. All units pass though there may be bad edge-cases
- Remove redundant `mod` operations
- Cleanup
=> BitOps fixes

src/SourceCode.Clay.Algorithms/SourceCode.Clay.Algorithms.csproj, src/SourceCode.Clay.Buffers/SourceCode.Clay.Buffers.csproj, src/SourceCode.Clay.Collections/SourceCode.Clay.Collections.csproj, src/SourceCode.Clay.Data/SourceCode.Clay.Data.csproj, src/SourceCode.Clay.IO/SourceCode.Clay.IO.csproj, src/SourceCode.Clay.Javascript/SourceCode.Clay.Javascript.csproj, src/SourceCode.Clay.Json/SourceCode.Clay.Json.csproj, src/SourceCode.Clay.OpenApi/OasSecurityScheme.cs, src/SourceCode.Clay.OpenApi/SourceCode.Clay.OpenApi.csproj, src/SourceCode.Clay.Security/SourceCode.Clay.Security.csproj, src/SourceCode.Clay.Text/SourceCode.Clay.Text.csproj, src/SourceCode.Clay.Threading/SourceCode.Clay.Threading.csproj, src/SourceCode.Clay/Sha1.cs, src/SourceCode.Clay/Sha256.cs, src/SourceCode.Clay/ShaUtil.cs, src/SourceCode.Clay/SourceCode.Clay.csproj, src/SourceCode.Clay/SourceCode.Clay.xml, tests/SourceCode.Clay.Tests/Sha1Tests.cs, tests/SourceCode.Clay.Tests/Sha256Tests.cs
- Perf
- Enable upper/lower `ToString` formats
- FxCop
=> Sha1 optimizations

src/SourceCode.Clay/Sha1.cs, src/SourceCode.Clay/Sha1Extensions.cs, src/SourceCode.Clay/Sha256.cs, src/SourceCode.Clay/Sha256Extensions.cs, src/SourceCode.Clay/SourceCode.Clay.xml
- Move core hashing methods out into extensions, so that `Sha1` does not keep an expensive static `SHA1` around
- Cleanup
=> Experiment: Decouple Sha

coverage.runsettings, src/SourceCode.Clay.Net.UrlTemplate/HttpClientUrlTemplateExtensions.cs, src/SourceCode.Clay.Net.UrlTemplate/SourceCode.Clay.Net.UrlTemplate.csproj, src/SourceCode.Clay.Net.UrlTemplate/TemplateCompiler.cs, src/SourceCode.Clay.Net.UrlTemplate/UriToken.cs, src/SourceCode.Clay.Net.UrlTemplate/UrlTemplateWebRequestExtensions.cs, src/SourceCode.Clay/SourceCode.Clay.csproj
Fix warnings.
Drop System.Memory version to 4.5.1 where possible.
Add runsettings for IDE code coverage.
=> System.Memory
